import type * as configTypes from "../types/configTypes";
import type { ADWebAuthConfig } from "@cityssm/ad-web-auth-connector/types";
import type * as docuShareConfig from "@cityssm/docushare/types";
export declare function getProperty(propertyName: "application.userDomain"): string;
export declare function getProperty(propertyName: "application.httpPort"): number;
export declare function getProperty(propertyName: "application.rootUrl"): string;
export declare function getProperty(propertyName: "reverseProxy.disableCompression"): boolean;
export declare function getProperty(propertyName: "reverseProxy.disableEtag"): boolean;
export declare function getProperty(propertyName: "reverseProxy.blockViaXForwardedFor"): boolean;
export declare function getProperty(propertyName: "reverseProxy.urlPrefix"): "";
export declare function getProperty(propertyName: "session.cookieName"): string;
export declare function getProperty(propertyName: "session.doKeepAlive"): boolean;
export declare function getProperty(propertyName: "session.maxAgeMillis"): number;
export declare function getProperty(propertyName: "session.secret"): string;
export declare function getProperty(propertyName: "authentication.source"): "ad-web-auth" | "Active Directory";
export declare function getProperty(propertyName: "authentication.adWebAuthConfig"): ADWebAuthConfig;
export declare function getProperty(propertyName: "authentication.activeDirectoryConfig"): configTypes.ActiveDirectoryConfig;
export declare function getProperty(propertyName: "permissions.canUpdate"): string[];
export declare function getProperty(propertyName: "customizations.applicationName"): string;
export declare function getProperty(propertyName: "customizations.contract.alias"): string;
export declare function getProperty(propertyName: "customizations.contract.aliasPlural"): string;
export declare function getProperty(propertyName: "customizations.contractCategory.alias"): string;
export declare function getProperty(propertyName: "customizations.contractCategory.aliasPlural"): string;
export declare function getProperty(propertyName: "customizations.contractParty.alias"): string;
export declare function getProperty(propertyName: "customizations.contractParty.aliasPlural"): string;
export declare function getProperty(propertyName: "customizations.notificationDays"): number;
export declare function getProperty(propertyName: "docuShare.isEnabled"): boolean;
export declare function getProperty(propertyName: "docuShare.rootURL"): string;
export declare function getProperty(propertyName: "docuShare.collectionHandle"): string;
export declare function getProperty(propertyName: "docuShare.server"): docuShareConfig.ServerConfig;
export declare function getProperty(propertyName: "docuShare.session"): docuShareConfig.SessionConfig;
